### ISSUE TITLE
whether the following operations are necessary

### ISSUE THREAD

**Issue by fzb408** [lhf12278/PFM-EKFP#1]
```  
if attn_mask is not None:
      #attn = torch.baddbmm(attn_mask, q, k.transpose(-2, -1))
      attn = torch.bmm(q, k.transpose(-2, -1))
      attn = softmax(attn,dim=-1)
      attn = attn*(attn_mask)
  else:
      attn = torch.bmm(q, k.transpose(-2, -1))
      attn = softmax(attn, dim=-1)
  #attn = softmax(attn, dim=-1)
```

**Comment by ysd199** [comment]
Yes, the operations are necessary.

**Comment by fzb408** [comment]
thank you!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lhf12278/PFM-EKFP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月19日(星期五) 晚上8:06
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [lhf12278/PFM-EKFP] whether the following operations are necessary (Issue #1)





 
Yes, the operations are necessary.
